backend:
  name: github
  repo: futuregerald/jekyll-base # Path to your Github repository
  branch: master # Branch to update
 
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads